(("default" . ((user-emacs-directory . "~/src/spacemacs")))
 ("doomemacs" . ((user-emacs-directory . "~/src/doomemacs")))
 ("spacemacs" . ((user-emacs-directory . "~/src/spacemacs")))
 ("efs" . ((user-emacs-directory . "~/src/efs")))
 )
