(("default" . ((user-emacs-directory . "~/src/spacemacs")))
 ("doomemacs" . ((user-emacs-directory . "~/src/doomemacs")
                 ("DOOMDIR" . "~/.config/doom")
                 ))
 ("spacemacs" . ((user-emacs-directory . "~/src/spacemacs")))
 ("efs" . ((user-emacs-directory . "~/src/efs")))
 ("lazycat" . ((user-emacs-directory . "~/src/manateelazycat")))
 )
