#!/usr/bin/env bash
set -eu
[[ "$(file -Lb --mime-type "$1")" =~ ^image ]] || exit 1   
exec /home/xin/.local/kitty.app/bin/kitty +kitten icat --silent --transfer-mode file --place "${2}x${3}@${4}x${5}" "$1"
# kitty +kitten icat --transfer-mode file --stdin no --place 41x22@39x1 file < /dev/null > /dev/tty