#!/usr/bin/env bash
# changed from knmac's dotfiles
# REF: https://github.com/knmac/.dotfiles/tree/master/lf/.config/lf

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
mkdir -p "$HOME/.cache/lf"

# # TODO: load preview scripts individually
# for f in "/home/xin/.config/lf/scripts/preview_*.sh"; do . $f; done
# source < (cat "/home/xin/.config/lf/scripts/preview_*.sh")

. "/home/xin/.config/lf/scripts/preview_metainfo.sh"
. "/home/xin/.config/lf/scripts/preview_videoinfo.sh"
. "/home/xin/.config/lf/scripts/preview_audioinfo.sh"
. "/home/xin/.config/lf/scripts/preview_video.sh"
. "/home/xin/.config/lf/scripts/preview_audio.sh"
. "/home/xin/.config/lf/scripts/preview_image.sh"
. "/home/xin/.config/lf/scripts/preview_text.sh"
. "/home/xin/.config/lf/scripts/preview_md.sh"
. "/home/xin/.config/lf/scripts/preview_doc.sh"
. "/home/xin/.config/lf/scripts/preview_docx.sh"
. "/home/xin/.config/lf/scripts/preview_excel.sh"
. "/home/xin/.config/lf/scripts/preview_epub.sh"
. "/home/xin/.config/lf/scripts/preview_pdf.sh"
. "/home/xin/.config/lf/scripts/preview_comic.sh"
. "/home/xin/.config/lf/scripts/preview_html.sh"
# . "/home/xin/.config/lf/scripts/preview_appimage.sh" # not working

# API
case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
    *.tgz|*.tar.gz)
        tar tzf "$1"
        ;;
    *.tar.bz2|*.tbz2)
        tar tjf "$1"
        ;;
    *.tar.txz|*.txz)
        xz --list "$1"
        ;;
    *.tar|*.tar.xz)
        tar tf "$1"
        ;;
    *.zip|*.jar|*.war|*.ear|*.oxt|*.apk)
        unzip -l "$1"
        ;;
    *.rar)
        unrar l "$1"
        ;;
    *.7z)
        7z l "$1"
        ;;
    *.deb)
        dpkg-deb -I "$1"
        ;;
    *.rpm)
        rpm -qip "$1"
        ;;
    # *.appimage|*.AppImage)
    #     preview_appimage "$1"
    #     ;;
    *.[1-8])
        man "$1" | col -b
        ;;
    *.o)
        nm "$1"
        ;;
	  *.ino)
		    preview_text --language=cpp "$1"
		    ;;
    *.so)
        readelf --notes "$1"
        ;;
    *.torrent)
        transmission-show "$1"
        ;;
    *.iso)
        iso-info --no-header -l "$1"
        ;;
    *.odt|*.ods|*.odp|*.sxw)
        odt2txt "$1"
        ;;
    *.doc)
        preview_doc "$1"
        ;;
    *.docx)
        preview_docx "$1"
        ;;
    *.xls|*.xlsx)
        preview_excel "$1"
        ;;
    *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|\
        *.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
        preview_audio "$1"
        ;;
    *.pdf)
        preview_pdf "$1" "$2" "$3" "$4" "$5"
        ;;
    *.epub)
        preview_epub "$1" "$2" "$3" "$4" "$5"
        ;;
    *.mobi)
        preview_metainfo "$1"
        ;;
    *.cbz|*.cbr|*.cbt)
        preview_comic "$1" "$2" "$3" "$4" "$5"
        ;;
    *.html|*.hml|*.xml)
        preview_html "$1" "$2" "$3" "$4" "$5"
        ;;
    *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|\
        *.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|\
        *.r[am]|*.rmvb|*.qt|*.divx)
        preview_video "$1" "$2" "$3" "$4" "$5"
        ;;
    *.scr)
        preview_metainfo "$1"
        ;;
    *.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif|*.tiff|*.ico)
        preview_image "$1" "$2" "$3" "$4" "$5"
        ;;
    *.svg)
        [ ! -f "${CACHE}.jpg" ] && \
            convert "$1" "${CACHE}.jpg"
        preview_image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
        ;;
    *.ino)
        preview_text --language=cpp "$1"
        ;;
    *.md|*.markdown)
        preview_md "$1"
        ;;
    *.six|*.sixel)
        cat "$1"
        ;;
    *)
        if [ -n "$(find "$1" -prune -size +1000000c)" ]; then
            preview_metainfo "$1"
        else
            preview_text "$1"
        fi
        ;;
esac
exit 0
