session_name: config
start_directory: ~/src/
windows:
  - window_name: spacemacs
    layout: main-vertical
    focus: true
    panes:
      - shell_command:
          - emacsclient -tc DotSpacemacs/.spacemacs
        focus: true
      - shell_command:
          - cd DotSpacemacs/
          - git status
      - shell_command:
          - cd spacemacs/
          - git pull
  - window_name: tmux
    start_directory: ~/src/DotFiles-Linux/.config/
    layout: main-vertical
    panes:
      - shell_command:
          - emacsclient -tc tmux/tmux.conf
        focus: true
      - shell_command:
          - emacsclient -tc tmuxp/config.yaml
      - shell_command:
          - lfcd tmuxp/
  - window_name: lf
    start_directory: ~/src/DotFiles-Linux/.config/lf/
    layout: main-vertical
    panes:
      - shell_command:
          - emacsclient -tc cmd
        focus: true
      - shell_command:
          - cmd: emacsclient -tc keybindings
      - shell_command:
          - cmd: lfcd .
      - shell_command:
          - cmd: lfcd ~/src/lf-sixel/etc/
  - window_name: foot
    start_directory: ~/src/DotFiles-Linux/.config/foot/
    layout: even-horizontal
    panes:
      - shell_command:
          - emacsclient -tc foot.ini
        focus: true
      - shell_command:
          - lfcd .
  - window_name: kitty
    start_directory: ~/src/DotFiles-Linux/.config/kitty/
    layout: even-horizontal
    panes:
      - shell_command:
          - emacsclient -tc kitty.conf
        focus: true
      - shell_command:
          - lfcd .
  - window_name: shell
    start_directory: ~/src/DotFiles-Linux/
    layout: main-vertical
    panes:
      - shell_command:
          - git status
      - shell_command:
          - emacsclient -tc .bashrc
        focus: true
      - shell_command:
          - emacsclient -tc .profile
  - window_name: emacs
    start_directory: ~/src/emacs/
    layout: even-horizontal
    panes:
      - shell_command:
          - git fetch
        focus: true
      - shell_command:
          - git tag | rg 29
