# ~/.tmuxinator/config.yml

name: config
# root: ~/src

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t write@home

windows:
  - system:
      root: ~/src/DotFiles-Linux
      layout: main-vertical
      panes:
        - emacsclient -tc .Xresources
        - emacsclient -tc .bashrc
        - emacsclient -tc .gitconfig        
  - emacs:
      root: ~/src/DotEmacs/my-lisps/init
      layout: tile
      panes:
        - emacsclient -tc xy-rcroot-look.el
        - emacsclient -tc xy-rcroot-enhance.el
        - emacsclient -tc xy-rcroot-history.el
        - emacsclient -tc xy-rcroot-complete.el
  - tmuxconf:
      root: ~/src/DotFiles-Linux
      layout: main-vertical
      panes:
        - emacsclient -tc .tmux.conf
  - tmuxinatorconf:
      root: ~/src/DotFiles-Linux/.tmuxinator
      layout: tile
      panes:
        - emacsclient -tc config.yml
        - emacsclient -tc aimmatdsp.yml
        - emacsclient -tc 18month.yml
        - emacsclient -tc statsug.yml

